# Model Building

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as ana

In [2]:
df = pd.read_csv("train_encoded.csv")

In [3]:
df.head()

,ExterQual,ExterCond,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,HeatingQC,CentralAir,KitchenQual,...,LandSlope_Mod,LandSlope_Sev,Utilities_NoSeWa,LotShape_IR2,LotShape_IR3,LotShape_Reg,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM
0,4,3,4,3,0,6,1,5,1,4,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,3,3,4,3,3,5,1,5,1,3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,4,3,4,3,1,6,1,5,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,3,3,3,4,0,5,1,4,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,4,3,4,3,2,6,1,5,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

# Separate features and target

In [4]:
X = df.drop("SalePrice",axis=1)

In [5]:
y = df['SalePrice']

In [6]:
X.shape

(1460, 196)

In [7]:
y.shape

(1460,)

In [8]:
X.columns

Index(['ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinType2', 'HeatingQC', 'CentralAir',
       'KitchenQual',
       ...
       'LandSlope_Mod', 'LandSlope_Sev', 'Utilities_NoSeWa', 'LotShape_IR2',
       'LotShape_IR3', 'LotShape_Reg', 'MSZoning_FV', 'MSZoning_RH',
       'MSZoning_RL', 'MSZoning_RM'],
      dtype='object', length=196)

In [9]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

# Train-Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42   #it is like a fixed seed , everytime there will be same split,same trainung data,same testing data and same result
)

In [12]:
X_train.shape

(1168, 196)

In [13]:
X_test.shape

(292, 196)

In [16]:
y_train.shape

(1168,)

In [18]:
y_test.shape

(292,)

# Feature Scaling 

Sab features ko ek similar scale par lana taaki koi feature sirf apni value ke size ki wajah se dominate na kare.

# Standard Scalar

z = x-u/sigma

mean = 0 

standard deviation = 1

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()

In [22]:
X_train_scaled = scaler.fit_transform(X_train)   #training data p fit learnns from the data mean , deviation, and transform use those values to scale the data

In [23]:
X_test_scaled = scaler.transform(X_test)

In [24]:
X_train_scaled.shape

(1168, 196)

In [25]:
X_test_scaled.shape

(292, 196)

In [27]:
print(type(X_train_scaled))

<class 'numpy.ndarray'>

# Linear Regression

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
lr = LinearRegression()

In [31]:
lr.fit(X_train_scaled,y_train)   #this fit trains the model on the training data

LinearRegression()

# Prediction

In [32]:
y_pred = lr.predict(X_test_scaled)

In [33]:
y_pred

array([ 151389.78454143,  346038.60713431,   98356.15714885,
        175867.29697507,  299822.71704297,   72795.10108638,
        232237.94716959,  144627.31868395,   59493.64613864,
        144598.48637892,  137210.46229901,   99825.88662877,
         55955.47500741,  236432.72058287,  165230.52126619,
        135223.01143669,  190695.0130703 ,  129005.31971204,
        130744.28468271,  224189.20574188,  136980.0791153 ,
        208574.44585245,  169353.47701408,  121630.34908596,
        202031.79580929,  128571.75149063,  197467.70557254,
         93895.14186993,  165129.75956186,  189049.60050181,
        140495.68639814,  295600.98083589,  247278.00176516,
        104609.58997721,  239855.07209955,  145400.98408126,
        144391.59332905,  202598.20249619,  306452.10933916,
         96492.36699013,  128044.33442951,  232004.71433266,
         95023.58074228,  348347.00233465,  133791.13859346,
        128557.78859549,   94113.66764248,  135560.57683344,
        396922.54066666,  131334.56405902,  115751.30510456,
        284514.73420817,  108620.74875561,  342629.4214491 ,
        150276.7589667 ,  250188.5603731 ,  202006.50907756,
        164484.3314168 ,  139589.19940815,   98490.44378207,
         53341.6156731 ,  170713.42125138,  324206.86820855,
        253068.34852447,  282495.03450988,  195525.2666476 ,
        101193.13006684,  296978.62987876,  127715.46296885,
        177792.21900046,  113788.07389596,  113686.30196358,
        101851.9790771 ,   25220.01702565,  457918.02877028,
        207374.8318312 ,  310522.80936801,  402664.88306062,
        142652.26755306,  122310.88192319,  116411.77141755,
         53791.80244445,  118612.66359162,   69409.68474645,
        157867.42137602,  140606.98174059,  269768.55120914,
        217512.67282949,  130340.46503329,  193724.07115321,
        152049.71253301,  153426.60770272,  189220.98299107,
        258030.2751676 ,  124793.32810429,  179319.77160338,
        180225.84235949,  154477.81738694,  216386.77110625,
        266569.93849798,  186455.60601587,  213092.78613783,
        304689.11940708,  145443.7694213 ,  199759.70299783,
        175441.84881717,  139423.77089395,  297723.55952915,
        152899.26501001,  190860.09381329,   25600.31259717,
        134973.96405135,  143945.23917399,  142772.76717222,
        212695.3592187 ,  126182.02695183,   93210.48694646,
         92903.68324369,  112276.99322247,  324036.00998445,
        117012.06278207,  141245.95269297,  183733.63944933,
        186279.12937412,  194681.36245429,  133080.938933  ,
        230992.80987376,  122280.91114532,  146863.86906554,
        174396.83682495,  184158.84522544,  333950.8329229 ,
        199753.94602779,  129133.08155206,   23788.90228873,
        356053.79359288,  352105.35994792,  147705.7960778 ,
        236276.02739493,  561458.55764994,  340353.43844308,
        126423.25158843,  178890.49055744,  149106.61534733,
        146950.33735665,  104217.59809967,  238000.42534216,
        197207.33185166,  125303.8054761 ,   51358.31665425,
         99652.18505503,  135285.63068008,  252243.44180733,
        169862.50357273,   88597.19470241,  113444.00747403,
        148955.92951657,  140155.39114216,   77637.18890842,
        128981.37542056,  202056.49707598,  116261.6904907 ,
        307103.03778824,  168374.954645  ,  109700.78951971,
        116924.15260182,  283405.89948382,  317007.90190378,
        414072.75339564,  221428.1395861 ,  345340.27826448,
         97774.30904779,  104672.86774394,  138742.68147922,
        317910.24094218,   90615.08113202,  134592.13838271,
        223296.64196677,  129343.46464312,  162680.45317865,
        189669.44998885,   95579.73314624,  121255.33256832,
        153336.36586765,  247514.14354452,  164927.92932146,
        277056.11843028,  231122.36421154,  216303.18107403,
         70442.08213953,  119719.50936037,   90222.80737519,
        168205.01795326,  169827.2636252 ,  220102.21431277,
        184669.4053957 ,  197672.20589398,   71837.87745867,
        197496.56112453,  114759.44277181,  268917.81120451,
        204987.81397444,  139977.73003935,  319803.55152702,
        193280.53434901,  114658.51712685,  231855.59843995,
        134356.11506757,  132124.41620969,   90345.50658918,
        227705.76077821,  135990.84311559,  107427.93104723,
        169921.05872054, -443493.54536305,  265650.50933236,
        214222.26546505,  147557.40575852,  180707.18192921,
         82756.407245  ,  129531.93941466,  232161.13713596,
        227612.76763749,   81527.55930696,  218924.33603669,
        158190.33153915,   64665.34218746,   73942.36751925,
        159880.76872497,  110027.8462468 ,   78113.97329922,
        166373.09544078,  112470.93489547,  134977.43864553,
        231447.24199203,  150445.98793522,  207745.58282754,
        159050.2404903 ,  237220.31997747,  101018.44494212,
        112924.04920008,  269785.3623732 ,  233346.34453318,
        463723.15097009,  194724.85701258,  150592.59678418,
        139749.07595761,  172605.1839293 ,  143439.6114545 ,
        107660.9049644 ,  187983.73314657,  164686.3007135 ,
        147829.21303944,   73159.57959921,  143687.76551482,
        139715.73640301,  110765.08192569,  128321.27486518,
        173635.68878015,  255676.8285554 ,  329767.86376616,
        185415.14978826,  119458.21680666,  249126.38572098,
        313485.95855787,  230737.63825155,  156534.29052269,
        136329.09865767,   88884.13413808,  168713.06559308,
        387690.2973416 ,  234354.21704749,  238537.28656734,
         82600.84697238,   79634.6161503 ,  141613.08285756,
        131474.19078525,  293749.08236593,  235059.20139363,
        133402.30666218,  203071.08896895,   84997.7868462 ,
        207587.90310342,  110279.29663004,  287413.74942061,
        179322.80783281,  212712.31990557,  144829.09024213,
        298817.17783199,  193420.63857095,  103070.10917967,
        106084.61018562])

In [34]:
print(y_pred[:10])

[151389.78454143 346038.60713431  98356.15714885 175867.29697507
 299822.71704297  72795.10108638 232237.94716959 144627.31868395
  59493.64613864 144598.48637892]

# Compare actual vc predicted prices

In [35]:
comparison = pd.DataFrame({
    "Actual Price":y_test.values,
    "Predicted Price":y_pred
})

In [36]:
comparison.head(10)

   Actual Price  Predicted Price
0        154500    151389.784541
1        325000    346038.607134
2        115000     98356.157149
3        159000    175867.296975
4        315500    299822.717043
5         75500     72795.101086
6        311500    232237.947170
7        146000    144627.318684
8         84500     59493.646139
9        135500    144598.486379

# Evaluation

In [38]:
from sklearn.metrics import (mean_absolute_error,mean_squared_error,r2_score)

In [39]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

MAE : 21704.894420757417
MSE : 2492805175.9616494
RMSE: 49927.99991950057
R² Score: 0.6750066283196821